---
title: "Correcciones de Sexta Ronda para José"
author: "http://synergy.vision/"
output: pdf_document
subtitle: 
fontsize: 12pt
---

```{r include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```


- Hacer pull a los cambios realizados.

# Ejercicio 1

La forma más sencilla para crear un objeto tipo data frame es usando el comando `data.frame()`, a este se le debe pasar los vectores, o variables que deben tener el mismo tamaño, y pueden ser de distintos tipos. En el gráfico que estas construyendo podrías usar $data.frame(Salario,Ausencia)$. 

Cuando creas un `ggplot()` debes pasar los datos guardados en un data frame como lo hiciste, y en el mapping es suficiente con especificar quienes son las variables que vas a usar de ese data frame para tus ejes `x` e `y`, puedes colocar `aes(x=Salario, y=Ausencia)`. Los títulos, nombres de las ejes, subtitulos y firmas deben ir dentro de `lab(title ='',x='', y='', caption='' )`, adicionalmente queremos que la plantilla sea la misma para todos esto lo hacen colocando `vision` y agregandole el credíto que coloque al inicio del documento, todo esto es para tener los mismos gráficos en todos los archivos. Observa las modificaciones que coloque en este ejercicio y aplicalas para todos los demás.

Se que en este ejercicio no te piden calcular el modelo de regresión lineal, pero me gustaría que lo colocaras, primero con realizando los calculos manuales con las fórmulas y luego usando los comando de `R` para realizar dichos cálculos

# Ejercicio 2

a) ¿Cómo se calcularía la recta de regresión lineal? colocar las fórmulas y aplicación de las mismas, luego hacer los calculos utilizando los comandos correspondientes con `R`, y decir que significa el modelo que se obtiene.

b) Escribir primero que representa el modelo de regresión lineal.

c) El error estándar se utiliza para medir la dispersión de un conjunto de observaciones respecto a la media, mide la variabilidad, o dispersión de los valores observados alrededor de la recta de regresión, la fórmula para calcularlo es 

$$S_e = \sqrt{\frac{\sum_{i=1}^n (Y_i- \hat Y_i)^2}{n-2}}$$

Para realizar su calculo primero debes calcular los valores estimados por el modelo de regresión encontrado, es decir los valores $\hat Y_i$ y luego aplicar la fórmula. Después que consigas dicho valor debes colocar como se calcula con `R`.

d) Realizar los cálculos de esta parte en `R`, manualmente.

# Ejercicio 3

a) ¿Cómo se calcularía la recta de regresión lineal? colocar las fórmulas y aplicación de las mismas, luego hacer los calculos utilizando los comandos correspondientes con `R`, y decir que significa el modelo que se obtiene.

b) Colocar : Es decir, si un capacitado obtuvo una calificación de prueba de 3.4, según el modelo de regresión este venderá 136.84 unidades.

# Ejercicio 4

b) ¿Cómo se calcularía la recta de regresión lineal? colocar las fórmulas y aplicación de las mismas, luego hacer los calculos utilizando los comandos correspondientes con `R`, y decir que significa el modelo que se obtiene.

# Ejercicio 5

a) ¿Cómo se calcularía la recta de regresión lineal? colocar las fórmulas y aplicación de las mismas, luego hacer los calculos utilizando los comandos correspondientes con `R`, y decir que significa el modelo que se obtiene.

b) 

El __coeficiente de determinación__ se cálcula con la fórmula siguiente

$$r^2 = 1- \frac{\sum_{i=1}^n (Y_i - \hat Y_i)^2}{\sum_{i=1}^n (Y_i - \overline Y)^2}$$

Y este nos dice el grado de asociación lineal entre las variables $X$ e $Y$. Dar una interpretación del resultado obtenido en el modelo de regresión ajustado. Realizar el cálculo de este manualmente y luego poner como se obtiene en `R`.

El __coeficiente de correlación__ es la raíz cuadrada del coeficiente de determinación $r=\sqrt{r^2}$. El signo de este valor dependera de la pendiente que se obtiene en el modelo de regresión. Realizar su cálculo mediante la fórmula y luego hacerlo con `R`, dar una interpretación del resultado que se obtiene y que representa en este problema.

# Ejercicio 6

a) ¿Cómo se calcularía la recta de regresión lineal? colocar las fórmulas y aplicación de las mismas, luego hacer los calculos utilizando los comandos correspondientes con `R`, y decir que significa el modelo que se obtiene.

b) Igual a la parte b) del ejercicio 5.

# Ejercicio 7

a) Colocar también $S_e=$ Error estándar de la estimación $\left( S_e = \sqrt{\frac{\sum_{i=1}^n Y_i^2 -a \sum_{i=1}^n Y_i-b\sum_{i=1}^n X_iY_i}{n-2}}\right)$ 

Para la prueba de hipótesis:

¿Cómo calculas el valor del estadístico en `R` y el valor crítico? hacer una representación gráfica para está prueba de hipótesis.

# Ejercicio 8

¿Cómo se calcularía la recta de regresión lineal? colocar las fórmulas y aplicación de las mismas, luego hacer los calculos utilizando los comandos correspondientes con `R`, y decir que significa el modelo que se obtiene.

Para la prueba de hipótesis:

¿Cómo calculas el valor del estadístico en `R` y el valor crítico? hacer una representación gráfica para está prueba de hipótesis.

# Ejercicio 9

Igual que las observaciones del ejercicio 7.









