---
title: "Correcciones de Tercera Ronda de Ejercicios"
author: "http://synergy.vision/"
output: pdf_document
subtitle: José
fontsize: 12pt
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Hacer pull a tus ejercicios.

- Las variables aleatorias deben colocarse en mayúscula y cursiva con `\mathcal{X}`

- El operador varianza y esperanza colocarlos con [] no con paréntesis.

Ejercicio 1 y 2

Colocar en la primera parte de la esperanza de la variable igual como lo hiciste en el ejercicio anterior, es decir, los valores que toma la variable por la probabilidad que la variable tome esos valores.

Hacer el calculo mediante comandos de R

- Crear un vector que guarde los valores posibles que puede tomar la variable.

- Crear otro vector que guarde las correspondientes probabilidades, y calcular esta esperanza mediante la suma del producto de estos dos vectores.

`sum(valores*probabilidades)`

Ejercicio 3

a) Decir con tus propias palabras porque es una distribución binominal.

Especificar los parámetros que usa cada comando

Ejemplo: `dbinom (q=0 size=15, prob=0.3)`

b) Colocar cada uno de estos cálculos manuales

$$
\begin{array}{rl}
P(\mathcal X=0) & =\frac{15!}{0!(15-0)!}\quad 0.3^0\times 0.75^{15-0}\\
& =\frac{15!}{15!}0.75^{15}\\
& =0.75^{15}\\
& =0.00474
\end{array}
$$

Nota: agregar que representa el comando `dbinom()` y `pbinom()`.

Ejercicio 4

Explicar brevemente porque $\lambda=4$

Para que las fórmulas no se vean tan pegadas colocar el comando `\vspace{3mm} en la fórmula prevía, no separarlas con \\.

d) pues las probabilidades $P(\mathcal X=0,2,4)$ quitarlo y colocarlas por separado $P(\mathcal X=0), P(\mathcal X=2),...$

Ejercicio 6)

Agregar el cálculo en R con la distribución normal estándar

Ejercicio 7)

La página para hacer las tablas es tablesgenerator.com, luego seleccionar Markdowntables (tablesgenerator.com/markdown_tables) y allí creas la tabla

Definir quien es $E_1$, $E_2$, $E_3$ y $E_4$. Te recomiendo definir $E_2$, $E_3$, $E_4$, $E_5$ acorde a los posibles peticiones de costos de pan, sea $E_2$ las ventas esperadas por 2 lotes de pan y así sucesivamente.

Ejercicio 8)

c) colocar cada uno de los cálculos

Ejercicio 9)  10)

Agregar el cálculo de la distribución normal estándar

b)3) $P(x_1<\mathcal{X}<x_2)=P(\mathcal{X}<x_2)-P(\mathcal{X}>x_1)$
escribir esta probabilidad en la 3era fórmula

hacer el cálculo con la estándarización

d)2) $P(\mathcal X=2\cup\mathcal X=3)=P(\mathcal X=2)+P(\mathcal X=3)$

Ejercicio 11)

Cuya probabilidad de que el crédito sea ceptado es de $p=0.8$ y por consiguiente de que no sea aceptado es de $q=0.2$

Explicar un poco como se puede aproximar a la distribución normal mediante la distribución binominal que es exactamente lo que usas.

Ejercicio 12)

Colocar el cálculo de la normal estándar en R

Colocar en la fórmula de c)3) $P(\mathcal Z<0.19)-P(\mathcal Z<-1.24)$

Ejercicio 13)

La variable aleatoria binominal es el número de exitos obtenidos al realizar un experimento bernoulli

La variable $\mathcal X$ que estas definiendo es Bernoulli con probabilidad de éxito $0.08$ 

Define una nueva variable aleatoria como el número de éxitos al realizar $n$ experimentos Bernoulli, en este caso los 10 motores con la muestra y el experimento Bernoulli indica si el motor es defectuoso o no.

$y=\#$ de motores defectuosos donde la prob. de que sea defectuoso es $p=0.08$

$E(y)=np=10\times(0.08)=0.8$  se espera que aproximadamente en promedio 1 sea defectuoso.

Ganancia esperada $\$100\times (1-0.08)-\$100(0.08)=84$




