---
title: "Correcciones de Segunda Ronda de Ejercicios"
author: "http://synergy.vision/"
output: pdf_document
subtitle: Yoselin
fontsize: 12pt
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

- Colocar `\displaystyle` en las fórmulas que tienen fracciones.}

- Colocar paréntesis con `\left` y `\right` para que queden acorde a la fórmula.

- Las variables aleatorias deben colocarse en mayúscula y cursiva con `\mathcal{X}`

- Cuando se colocan comandos en R se deben colocar los parámetros que usan, especificarlos en cada caso.



**Ejercicio 19**

- Especificar los parámetros $\mu$ y $\sigma^2$ en $\mathcal{N} (900,400)$

$$\mathcal{N}(\mu=400,\sigma^2=400)$$

- Especificar igualmente los parámetros de los comandos usados

pnorm(q=   , mean=   , sd=   )

- Describir palabras que significan los resultados obtenidos.

**Ejercicio 20**

b) Responder de acuerdo a la esperanza encontrada en la parte a) quitar lo del valor estándar ¿Por qué lo colocaste?

**Ejercicio 21**

$$
\begin{array}{rl}
E(y^2)= &\int_\infty^\infty y^2 f(y) d(y)\\
= & \int_0^1 y^2 2(1-y)dy
\end{array}
$$

- Cuando se hace evaluación de la integral colocar la barra | de la siguiente forma

`\Big|`

- El operador varianza y esperanza colocarlos con [] no con paréntesis.

**Ejercicio 22**

- Cuando coloques sumatorias colocarlas con `\displaystyle`

- La P que representa probabilidad colocarla como **P**

**Ejercicio 23**

- Sea Y el número de estudiantes con tarjetas de crédito mayor a $7000 y sea X una variable aleatoria Bernoulli de la siguiente forma

$$
\mathcal{X}=\left\{
\begin{array}{rl}
1 & \text{si el estudiante tiene tarjeta de crédito mayor a 7000 dólares}\\
0 & \text{si no}
\end{array}\right.
$$


$P(X=1)=0.09$ (Probabilidad de tener un balance en sus tarjetas de crédito mayor a $7000)

$P(X=0)=0.91$ (Probabilidad de tener un balance inferior a $7000)

**Ejercicio 24**

Definir una variable aleatoria hipergeometrica que consta de dos grupos, los trabajadores de Hawai y los trabajadores de Texas (dos grupos disjuntos) y definirla como el número de trababjadores que trabajan en a fábrica de Hawai.

donde $$P(X=x)\frac{\displaystyle\binom{r}{x}\displaystyle\binom{n-r}{k-x}}{\displaystyle\binom{n}{k}}$$




Luego estandarizarlos y consigues el valor de X.  No partiendo de la estandarización como lo hiciste.

**Ejercicio 36**

Explicar estandarización.



