---
title: "Ejercicios de Prueba de Hipótesis 2"

subtitle: "Diplomado de Probabilidad y Estadística Matemática en R"
author: "http://synergy.vision/"
output:
  pdf_document:
      toc: yes
      toc_depth: 4
      includes:
        in_header: ./preambulo.tex
  html_document: default
fontsize: 12pt
---

# Ejercicio 1

La hipótesis nula apropiada para la prueba descrita es:

A. $H_0:\mu=3$horas

B. $H_0:\mu\le3$horas

C. $H_0:\mu\ge3$horas

# Ejercicio 2

Esto es un:

A. prueba de una cola.

B. Prueba de dos colas.

C. prueba de comparaciones pareadas. 

# Ejercicio 3

La estadística $z$ calculada es:

A. -2.67.

B. +0.33.

c. +2.67.

# Ejercicio 4

El valor (es) $z$ crítico de la estadística de prueba es (son):

A. -1.96.

B. +1.96.

C. $\pm$1.96.

# Ejercicio 5

El intervalo de confianza del 95% para la media de la población es:

A. {1.00<$\mu$<3.50}.

B. {0.54<$\mu$<4.46}.

C. {2.13<$\mu$<2.87}.

# Ejercicio 6

El analista debería más apropiadamente:

A. rechaza la hipótesis nula.

B. no puede rechazar la hipótesis nula.

C. no llegar a ninguna conclusión porque no se dio la desviación estándar de la muestra.

# Ejercicio 7

Se realizó un estudio para determinar si la desviación estándar de los costos mensuales de mantenimiento de un avión Pepper III es de \$ 300. Una muestra de 30 Pepper Ills tuvo un costo mensual de mantenimiento promedio de \$ 3,025 y una desviación estándar de \$ 325. Con un nivel de significancia del 5%, cuál de los siguientes es el más apropiado. Conclusión con respecto a diferencia entre el valor hipotético de la varianza poblacional y la varianza muestral?

A. La población y las variaciones de muestra son significativamente diferentes.

B. La población y las variaciones de muestra no son significativamente diferentes.

C. No hay pruebas que puedan usarse para probar las diferencias de varianza en  muestras pequeñas.


Se tomaron dos muestras de dos poblaciones normalmente distribuidas. Para la primera muestra, la media fue de \$ 50 y la desviación estándar fue de \$ 5. Para la segunda muestra, el promedio fue \$ 55 y la desviación estándar fue de \$ 6. La primera muestra consta de 25 observaciones y la segunda muestra consta de 36 observaciones. {Nota: en las preguntas a continuación, los subíndices "1"
y "2" indica la primera y la segunda muestra, respectivamente).

# Ejercicio 8

Considere las hipótesis estructuradas como $H_0:\mu_1=\$48$ contra $H_a:\mu_1\neq\$48$. A un 1% de nivel de significancia, la hipótesis nula:

A. no puede ser rechazado.

B. debe ser rechazado.

C. no puede ser probado usando esta muestra de información provista.

# Ejercicio 9

Utilizando un nivel de significancia del 5% y una estructura de prueba de hipótesis de $H_0:\sigma^2_1\le24$ contra $H_a:\sigma^2_1>24$,la hipótesis nula: 

A. no puede ser rechazado.

B. debe ser rechazado.

C. no puede ser probado usando esta muestra de información provista.

# Ejercicio 10

Considere las hipótesis estructuradas como $H_0:\mu_1\le\$48$ contra $H_a:\mu_1>\$48$. Con un nivel de significancia del 5%, la hipótesis nula:

A. no puede ser rechazado.

B. debe ser rechazado.

C. no puede ser probado usando la información de muestra proporcionada.

# Ejercicio 11

Usar un nivel de significancia del 5% para una prueba del nulo de $H_0:\sigma^2_1=\sigma^2_2$ contra la alternativa de $H_a:\sigma^2_1\neq\sigma^2_2$, la hipótesis nula:

A. no puede ser rechazado.

B. debe ser rechazado.

C. no puede ser probado usando la información de muestra proporcionada.

# Ejercicio 12

Si el nivel de significancia de una prueba es 0.05 y la probabilidad de un error de Tipo II es 0. 15, ¿cuál es el poder de la prueba?

A. 0.850.

B. 0.950.

c. 0.975.

# Ejercicio 13

¿Cuál de las siguientes afirmaciones sobre las distribuciones F y chi-cuadrado
es menos precisa? Ambas distribuciones:

A. son asimétricos.

B. están limitados por cero a la izquierda.

C. tienen medios que son menores que sus desviaciones estándar.

# Ejercicio 14

El estadístico de prueba apropiado para una prueba de igualdad de varianzas para dos variables aleatorias distribuidas normalmente, basadas en dos aleatorias independientes muestras, es el:

A. Prueba $t$.

B. Prueba $F$.

C. Prueba $X^2$.

# Ejercicio 15

La estadística de prueba apropiada para probar la hipótesis de que la varianza de un la población distribuida normalmente es igual a 13 es la:

A. Prueba $t$.

B. Prueba $F$.

C. Prueba $X^2$.

# Ejercicio 16

William Adams quiere probar si los rendimientos mensuales medidos en los últimos cinco años son iguales para dos acciones. Si asume que las distribuciones de devoluciones son normales y tienen las mismas variaciones, el tipo de prueba y estadístico de prueba se describen mejor como:

A. prueba de comparaciones pareadas, estadística $t$.

B. prueba de comparaciones pareadas, estadística $F$.

C. diferencia en la prueba de medios, estadística $t$.

# Ejercicio 17

¿Cuál de las siguientes suposiciones es menos probable que se requiera para la diferencia en la prueba de medios basada en dos muestras?

A. Las dos muestras son independientes.

B. Las dos poblaciones se distribuyen normalmente.

C. Las dos poblaciones tienen varianzas iguales.

# Ejercicio 18

Para una prueba de hipótesis con una probabilidad de un error de Tipo II del 60% y una probabilidad de un error de Tipo I del 5%, cuál de las siguientes afirmaciones es más precisa?

A. El poder de la prueba es del 40%, y hay un 5% de probabilidad de que la prueba la estadística excederá los valores críticos.

B. Hay un 95% de probabilidad de que la estadística de prueba se encuentre entre la crítica valores si esta es una prueba de dos colas.

C. Hay un 5% de probabilidad de que la hipótesis nula sea rechazada cuando
realmente cierto, y la probabilidad de rechazar el nulo cuando es falso es
40%.
