---
title: "Ejercicio de Variables Aleatorias y Prueba de Hipótesis"
subtitle: "Diplomado de Probabilidad y Estadística Matemática en R"
author: "http://synergy.vision/"
output:
  pdf_document:
      toc: yes
      toc_depth: 4
      includes:
        in_header: ./preambulo.tex
  html_document: default
fontsize: 12pt
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

\newpage

# Variables aleatorias 

#Ejercicio 1

Una muestra aleatoria simple es una muestra extraída de tal manera que cada miembro de la población tiene:

A. alguna posibilidad de ser seleccionado en la muestra.

B. la misma posibilidad de ser incluido en la muestra.

C. 1% de probabilidad de ser incluido en la muestra.

# Ejercicio 2

El error de muestreo se define como:

A. un error que ocurre cuando se dibuja una muestra de menos de 30 elementos.

B. un error que ocurre durante la recopilación, grabación y tabulación de datos.

C. la diferencia entre el valor de una muestra estadística y el valor del parámetro de población correspondiente

# Ejercicio 3 

La edad media de los candidatos CFA es de 28 años. La edad media de una muestra aleatoria de 100 candidatos es de 26.5 años. La diferencia de 1.5 años se llama:

A. error aleatorio.

B. error de muestreo.

C. error poblacional

# Ejercicio 4

Si $n$ es grande y la desviación estándar de la población es desconocida, el error estándar de la distribución muestral de la media muestral es igual a:

A. Desviación estándar de la muestra dividida por el tamaño de la muestra.

B. Desviación estándar de la población multiplicada por el tamaño de la muestra.

C. muestra la desviación estándar dividida por la raíz cuadrada del tamaño de la muestra.

# Ejercicio 5

El error estándar de la distribución de muestreo de la media muestral para un tamaño de muestra de $n$ extraído de una población con una media de $\mu$ y una desviación estándar de $\sigma$ es:

A. Desviación estándar de la muestra dividida por el tamaño de la muestra.

B. muestra la desviación estándar dividida por la raíz cuadrada del tamaño de la muestra.

C. Desviación estándar poblacional dividida por la raíz cuadrada del tamaño de la muestra.

# Ejercicio 6

Para aplicar el teorema del límite central a la distribución muestral de la media muestral, la muestra generalmente se considera grande si $n$ es mayor que:

A. 20.

B. 25.

C. 30.

# Ejercicio 7

Supongamos que una población tiene una media de 14 con una desviación estándar de 2. Si se extrae una muestra aleatoria de 49 observaciones de esta población, el error estándar de la media muestral es el más cercano a:

A. 0.04

B. 0.29

C. 2.00

# Ejercicio 8

La media de la población es 30 y la media de una muestra de tamaño 100 es 28.5. La varianza de la muestra es 25. El error estándar de la media muestral es el más cercano a:

A. 0.05

B. 0.25

C. 0.50

# Ejercicio 9

Una muestra aleatoria de 100 clientes de computadoras consumió un promedio de \$ 75 en la tienda. Suponiendo que la distribución es normal y la desviación estándar de la población es de \$ 20, el intervalo de confianza del 95% para la media de la población es el más cercano a:

A. \$ 71.08 a \$ 78.92.

B. \$ 73.89 a \$ 80.11.

C. \$ 74.56 a \$ 79.44.

# Ejercicio 10

Best Computers, Inc., vende computadoras y partes de computadoras por correo. Una muestra de 25 pedidos recientes mostró que el tiempo medio requerido para enviar estos pedidos fue de 70 horas con una desviación estándar de muestra de 14 horas. Suponiendo que la población se distribuye normalmente, el intervalo de confianza del 99% para la media de la población es:

A. 70 ± 2.80 horas.

B. 70 ± 6.98 horas.

C. 70 ± 7.83 horas.

# Ejercicio 11

La distribución de muestreo de una estadística es la distribución de probabilidad compuesta de todos los posibles:

A. observaciones de la población subyacente.

B. estadísticas de muestra calculadas a partir de muestras de distintos tamaños extraídas de la misma población.

C. estadísticas de muestra calculadas a partir de muestras del mismo tamaño extraídas de la misma población.

# Ejercicio 12

La muestra de las relaciones deuda / capital de 25 bancos estadounidenses que cotizan en bolsa a nivel fiscal fin de año 2003 es un ejemplo de:

A. una estimación puntual.

B. datos transversales.

C. una muestra aleatoria estratificada.

# Ejercicio 13

¿Cuál de las siguientes opciones es menos probable que sea una propiedad deseable de una estimación?

A. Confiabilidad.

B. Eficiencia.

C. Consistencia.

# Ejercicio 14

Si la varianza de la distribución muestral de un estimador es menor que todos los demás estimadores insesgados del parámetro de interés, el estimador es:

A. eficiente.

B. imparcial.

C. consistente.

# Ejercicio 15

¿Cuál de las siguientes opciones es menos probable que sea una propiedad de la distribución t de Student?

A. y los grados de libertad se hacen más grandes, la varianza se acerca a cero.

B. Se define por un solo parámetro, los grados de libertad, que es igual a $n-1$.

C. Tiene más probabilidad en las colas y menos en el pico que una distribución normal estándar.

# Ejercicio 16

Un analista que utiliza datos históricos que no estaban disponibles públicamente en el período de tiempo que se está estudiando tendrá una muestra con:

A. parcialidad de anticipación.

B. Sesgo de período de tiempo.

C. sesgo de selección de muestra.

# Ejercicio 17

El intervalo de confianza del 95% de la media muestral de la edad de los empleados de una corporación importante es de 19 años a 44 años según una estadística z. La población de empleados es más de 5.000 y el tamaño de muestra de esta prueba es 100. Suponiendo que la población normalmente se distribuye

A. 1.96.

B. 2.58.

C. 6.38

# Ejercicio 18

¿Cuál de los siguientes está *más estrechamente* relacionado con el sesgo de supervivencia?

A. Estudios de precio por libro.

B. Estudios de muestreo de bonos estratificados.

C. Estudios de desempeño de fondos mutuos.

# Ejercicio 19

¿Cuál es la estadística de prueba más apropiada para construir intervalos de confianza para la media poblacional cuando la población está distribuida normalmente, pero la varianza es desconocida?

A. La estadística $z$ en $\alpha$ con $n$ grados de libertad.

B. La estadística $t$ en $\alpha /2$ con $n$ grados de libertad.

C. La estadística $t$ en $\alpha /2$ con $n - 1$ grados de libertad.

# Ejercicio 20

Cuando se estima un intervalo de confianza para la media poblacional de una distribución no normal cuando se desconoce la varianza de la población y el tamaño de la muestra es grande $(n> 30)$, un analista puede usar aceptablemente:

A. bien una estadística $z$ o una estadística $t$.

B. solo una estadística $z$ en $\alpha$ con $n$ grados de libertad.

C. solo una estadística t en $\alpha /2$ con $n$ grados de libertad.

# Ejercicio 21

Jenny Fox evalúa a los gerentes que tienen una desviación estándar de la población de la sección transversal de rendimientos del 8%. Si los retornos son independientes entre los gerentes, ¿qué tan grande de una muestra necesita Fox, entonces el error estándar de la muestra es de 1.265%?

A. 7.

B. 30.

C. 40.

# Ejercicio 22

Los rendimientos anuales de las acciones pequeñas tienen una media poblacional del 12% y una desviación estándar de la población del 20%. Si los rendimientos se distribuyen normalmente, un intervalo de confianza del 90% en los rendimientos medios durante un período de 5 años es:

A. 5.40% a 18.60%.

B. -2.75% a 26.75%.

C. -5.52% a 29.52%.

# Ejercicio 23

Usando un muestreo aleatorio, un gerente quiere construir una cartera de 50 acciones que se aproximará a los rendimientos de un amplio índice de mercado que contiene 200 acciones. Explique cómo podría usar el muestreo aleatorio simple y el muestreo aleatorio estratificado para seleccionar poblaciones del índice y las posibles ventajas del muestreo aleatorio estratificado.

# Ejercicio 24

Un analista ha tomado una muestra aleatoria de 50 observaciones de una población para la cual quiere estimar el promedio de la población. Ella cree que la distribución de esta población está negativamente sesgada.

A. ¿Puede usar la media muestral para estimar la media poblacional y construir un intervalo de confianza? Explique.

B. ¿Cuáles son las propiedades estadísticas deseables de un estimador?

C. ¿Cuál de estas propiedades posee la muestra como un estimador de la media de la población?

# Ejercicio 25

Una muestra aleatoria de las estimaciones de ganancias de los analistas tiene una media de \$ 2.84 y una desviación estándar de \$ 0.40. ¿Qué podemos decir sobre el intervalo de confianza del 90% para las ganancias del próximo período si:

A. ¿el tamaño de muestra es 20?

B. ¿el tamaño de muestra es 40?

¿Qué enunciado probabilístico podríamos hacer al nivel de confianza del 90%? si:

C. ¿el tamaño de muestra fue 15?

D. ¿el tamaño de muestra fue 60?

\newpage

# Prueba de hipótesis 

# Ejercicio 1

¿Cuál de las siguientes afirmaciones sobre la prueba de hipótesis es más precisa?

A. Un error Tipo II rechaza el nulo cuando es realmente verdadero.

B. El nivel de significancia es igual a uno menos la probabilidad de un error de Tipo I.

C. Una prueba de dos vías con un nivel de significancia del 5% tiene valores $z$-críticos de $\pm1.96.$

\newpage
    
# Ejercicio 2

¿Cuál de las siguientes afirmaciones sobre la prueba de hipótesis es menos precisa?

A. El poder de la prueba = 1 - P $(error Tipo II).

B. Si la estadística $z-computada = -2$ y el valor $z-crítico = -1 .96$, la hipótesis es rechazada.

C. La estadística $z-calculada$ para una prueba de una muestra simple cuando la varianza poblacional es conocida:

$$z=\displaystyle\frac{\overline X-\mu_0}{\frac{\sigma^2}{\sqrt{n}}}$$

\newpage

Use la siguiente información para responder las preguntas 3 a 7.

Austin Roberts cree que el precio promedio de las casas en el área es mayor a \$145,000.

Una muestra aleatoria de 36 casas en el área tiene un precio promedio de \$149,750.  La desviación estándar La población es de \$24,000, y Roberts quiere realizar una prueba de hipótesis a un nivel de 1% del significado.

# Ejercicio 3

La hipótesis alternativa apropiada es:

A. $H_a: \mu < \$145,000.$

B. $H_a: \mu \ge \$145,000.$

C. $H_a: \mu > \$145,000.$

\newpage

# Ejercicio 4

El valor de la estadística de prueba calculada es más cercano a:

A. 0.67.

B. 1.19.

C. 4.00.

\newpage

# Ejercicio 5

¿Cuál de los siguientes describe con más precisión la estructura de prueba adecuada?

A. Prueba de dos colas.

B. Prueba de una cola.

C. Prueba Chi-cuadrado.

\newpage

# Ejercicio 6

El valor crítico de la estadística z es:

A. $\pm1.96.$

B. $+2.33.$

C. $\pm2.33.$

\newpage

# Ejercicio 7

Con un nivel de importancia del 1%, Roberts debería:

A. rechaza la hipótesis nula.

B. no puede rechazar la hipótesis nula.

C. ni acepto ni rechazo la hipótesis nula.

\newpage

Use la siguiente información para responder las preguntas 8 a 13.

Un analista está realizando una prueba de hipótesis para determinar si el tiempo medio empleado en la investigación de inversión es diferente de tres horas por día. La prueba se realiza en el 5% nivel de significancia y utiliza una muestra aleatoria de 64 administradores de cartera, donde el tiempo medio dedicado a la investigación es de 2.5 horas.La desviación estándar de la población  es 1. 5 horas.

# Ejercicio 8

La hipótesis nula apropiada para la prueba descrita es:

A. $H_0:\mu=3hours.$

B. $H_0:\mu\le3hours.$

C. $H_0:\mu\ge3hours.$

\newpage

# Ejercicio 9

Esto es un:

A. prueba de una cola.

B. Prueba de dos colas.

C. prueba de comparaciones pareadas.

\newpage

# Ejercicio 10

La estadística z calculada es:

A. $-2.67.$

B. $+0.33.$

C. $+2.67.$

\newpage

# Ejercicio 11

El valor z crítico de la estadística de prueba es (son):

A. $-1.96.$

B. $+1.96.$

C. $\pm1.96.$

\newpage

# Ejercicio 12

El intervalo de confianza del 95% para la media de la población es:

A. ${1.00<\mu<3.50}.$

B. ${0.54<\mu<4.46}.$

C. ${2.13<\mu<2.87}.$

\newpage

# Ejercicio 13

El analista debería más apropiadamente:

A. rechaza la hipótesis nula.

B. no puede rechazar la hipótesis nula.

C. no llegar a ninguna conclusión porque no se dio la desviación estándar de la muestra.

\newpage

# Ejercicio 14

Se realizó un estudio para determinar si la desviación estándar de la información mensual los costos de mantenimiento de un avión Pepper III son de \$300. Una muestra de 30 Pepper IIIs tuvo un costo de mantenimiento mensual promedio de \$3,025 y una desviación estándar de \$325. Usando un nivel de significancia del 5%, cuál de los siguientes es la más apropiada con respecto a la diferencia entre el valor hipotético de la varianza poblacional y la varianza muestral?

A. La población y las variaciones de muestra son significativamente diferentes.

B. La población y las variaciones de muestra no son significativamente diferentes.

C. No hay muestras que puedan usarse para probar las diferencias de varianza en pequeñas muestras.

\newpage

Use la siguiente información para responder las preguntas 1 a la 18.
Se tomaron dos muestras de dos poblaciones normalmente distribuidas. Para la primera muestra, el promedio fue de \$50 y la desviación estándar fue de \$5. Para la segunda muestra, el promedio fue \$55 y la desviación estándar fue de \$6. La primera muestra consiste en 25 observaciones y la segunda muestra consiste en 36 observaciones. (Nota: en las preguntas a continuación, los subíndices "1" y "2" indica la primera y la segunda muestra, respectivamente)

# Ejercicio 15

Considere la hipótesis estructurada como $H_0:\mu_1=\$48$ frente a $H_a:\mu_1\$48.$ A un nivel de significación del 1%, la hipótesis nula:

A. no puede ser rechazado.

B. debe ser rechazado.

C. no puede ser probado usando esta muestra de información provista.

\newpage

# Ejercicio 16

Utilizando un nivel de significancia del 5% y una estructura de prueba de hipótesis de $H_0:\sigma^2_1\le24$ contra $H_a:\sigma^2_1>24$, la hipótesis nula:

A. no puede ser rechazado.

B. debe ser rechazado.

C. no puede ser probado usando esta muestra de información provista.

\newpage

# Ejercicio 17

Considere la hipótesis estructurada como $H_0:\mu_1\le\$48$ frente a $H_a:\mu_1> \$ 48$. Con un nivel de significancia del 5%, la hipótesis nula:

A. no puede ser rechazado.

B. debe ser rechazado.

C. no puede ser probado usando la información de muestra proporcionada.

\newpage

# Ejercicio 18

Utilizando un nivel de significancia del 5% para una prueba del nulo de $H_0:\sigma^2_1=\sigma^2_2,$ contra la alternativa de $H_a:\sigma^2_1\ne\sigma^2_2,$ la hipótesis nula:

A. no puede ser rechazado.

B. debe ser rechazado.

C. no puede ser probado usando la información de muestra proporcionada.

\newpage

# Ejercicio 19

Si el nivel de significancia de una prueba es 0.05 y la probabilidad de un error de Tipo II es 0.15, ¿cuál es el poder de la prueba?

A. 0.850.

B. 0.950.

C. 0.975.

\newpage

# Ejercicio 20

¿Cuál de las siguientes afirmaciones sobre la distribución F y la distribución de Chi cuadrado  es menos precisa? Ambas distribuciones:

A. son asimétricos.

B. están limitados por cero a la izquierda.

C. tienen medios que son menores que sus desviaciones estándar.

\newpage

# Ejercicio 21

El estadístico de prueba apropiado para una prueba de igualdad de varianzas para dos variables aleatorias distribuidas normalmente, basadas en dos muestras aleatorias independientes, es el:

A. $t-test.$

B. $F-test.$

C. $X^2test.$

\newpage

# Ejercicio 22

La estadística de prueba apropiada para probar la hipótesis de que la varianza de un la población normalmente distribuida es igual a 13 es la:

A. $t-test.$

B. $F-test.$

C. $X^2test.$

\newpage

# Ejercicio 23

William Adams quiere probar si los rendimientos mensuales medios en los últimos cinco años son iguales para dos acciones. Si él supone que las distribuciones de devoluciones son normales y tienen las mismas variaciones, el tipo de prueba y la estadística de prueba son las mejores descritas como:

A. prueba de comparaciones pareadas, estadística-t.

B. prueba de comparaciones pareadas, estadística-F.

C. diferencia en la prueba de medios, estadística-t.

\newpage

# Ejercicio 24

¿Cuál de las siguientes suposiciones es menos probable que se requiera para la diferencia en la prueba de medios basada en dos muestras?

A. Las dos muestras son independientes.

B. Las dos poblaciones se distribuyen normalmente.

C. Las dos poblaciones tienen varianzas iguales.

\newpage

# Ejercicio 25

Para una prueba de hipótesis con una probabilidad de un error tipo II del 60% y una probabilidad de un error Tipo I de 5%, ¿cuál de las siguientes afirmaciones es más precisa?

A. El poder de la prueba es del 40%, y hay un 5% de probabilidad de que la prueba la estadística excederá los valores críticos.

B. Hay un 95% de probabilidad de que la estadística de prueba se encuentre 
entre el valor critico si esta es una prueba de dos colas.

C. Hay un 5% de probabilidad de que la hipótesis nula sea rechazada cuando
es realmente cierto, y la probabilidad de rechazar el nulo cuando es falso es 40%.

\newpage

# Ejercicio 26

Ralph Rollins, un investigador, cree que las acciones de las empresas que han aparecido en un periódico financiero determinado con un titular positivo y la historia regresan más sobre una base ajustada al riesgo. Recopila datos sobre el rendimiento ajustado al riesgo para estas
existencias durante los seis meses posteriores a su aparición en la portada, y los datos sobre el riesgo ajustados retornos para una muestra del mismo tamaño de empresas con características similares a las empresas de portada combinadas por período de tiempo.

A. Indique las probables hipótesis nula y alternativa para una prueba de su creencia.

B. ¿Es esta una prueba de una o dos colas?

C. Describe los pasos para probar una hipótesis como la nula que indicaste en la parte A.

\newpage

# Ejercicio 27

Para cada una de las siguientes hipótesis, describa la prueba apropiada, identifique la estadística de prueba apropiada y explique en qué condiciones debe rechazarse la hipótesis nula.

A. Un investigador tiene rendimientos de más de 52 semanas para un índice de gas natural y para un índice de reservas de petróleo y quiere saber si los retornos semanales son iguales. Supongamos que los rendimientos son aproximadamente normales repartido.

B. Un investigador tiene dos muestras independientes que están distribuidas de manera aproximadamente normal. Ella desea comprobar si los valores medios de las dos variables aleatorias son iguales y supone que las varianzas de las poblaciones de las que se extrajeron las dos muestras son iguales. Como pregunta adicional aquí, ¿cómo se deben calcular los grados de libertad?

C. Un investigador desea determinar si las varianzas poblacionales de dos variables aleatorias normalmente distribuidas son iguales en función de dos tamaños de tamaños $n_1$ y $n_2$. Como una pregunta adicional aquí, ¿cómo deberían calcularse los grados de libertad?

D. Un investigador quiere probar si la varianza de una población distribuida normalmente es igual a 0.00165. Como pregunta adicional aquí, ¿cómo deberían calcularse los grados de libertad?

\newpage

# Ejercicio 28

De un total de 10,200 préstamos otorgados por una unión de crédito de empleados del Estado en el último periodo de cinco años, se muestrearon 350 para determinar qué proporción de los préstamos se otorgaron a mujeres.  Esta muestra indicó que el 39% de los créditos fue dado a empleadas.  Un censo completo de préstamos de hace cinco años mostraba que el 41% de los prestarios eran mujeres.  A un nivel de significancia del 0.02, ¿puede concluir que la proporción de préstamos otorgados a mujeres ha cambiado significativamente en los últimos cinco años?

\newpage

# Ejercicio 29

Algunos teóricos financieros creen que los precios diarios del mercado de valores constituyen una "caminata aleatoria con tendencia positiva".  Si esto es correcto, entonces el promedio industrial Dow Jones debería mostrar una ganancia en más del 50% de todos los días de actividad financiera.  Si el promedio se incrementó en 101 de 175 días escogidos aleatoriamente, ¿qué piensa de la teoría sugerida?  Use un nivel de significancia de 0.01.

\newpage

# Ejercicio 30

Rick Douglas, el nuevo gerente de Food Barn, está interesado en el porcentaje de clientes totalmente satisfechos con la tienda.  El gerente anterior tenía el 86% de clientes totalmente satisfechos y Rick asegura que lo mismo se cumple hoy.  Rick obtuvo una muestra de 187 clientes y encontró que 157 estaban satisfechos por completo.  Con un nivel de significancia del 1%, ¿existe evidencia de que la afirmación de Rick es válida?

\newpage

# Ejercicio 31

La corredora de bienes raíces Elaine Snyderman tomó una muestra aleatoria de 12 hogares de un prestigiado suburbio de Chicago y encontró que el valor de mercado promedio estimado era \$780,000 con una desviación estándar de \$49,000.  Pruebe la hipótesis de que para todas las casas del área, el valor estimado medio es \$825,000, hipótesis alternativa de que es menor que \$825,000.  Utilice el nivel de significancia de 0.05.

\newpage

# Ejercicio 32

Con la caída del mercado petrolero de principios de 1986, los educadores del Texas se preocuparon por la forma en que las pérdidas resultantes en los ingresos del Estado (estimadas en cerca de \$100 millones por cada disminución de un dólar en el precio del barril de petróleo) afectarían sus presupuestos.  La directiva estatal de educación pensaba que la situación no sería crítica en tanto pudieran estar razonablemente seguros de que el precio permanecería arriba de \$18 por barril.  Encuestaron a 13 economistas especializados en el mercado del petróleo, elegidos al azar, y les pidieron que predijeran qué tanto bajarían los precios antes de repuntar.  Las 13 predicciones promediaron \$21.60, con una desviación estándar de \$4.65.  Para un nivel $\alpha=0.01,$ ¿es la predicción promedio significativamente mayor que \$18.00? ¿Debe la directiva de educación concluir que es improbable una crisis presupuestaria? Explique su respuesta.

\newpage

# Ejercicio 33

En un día promedio. alrededor del 5% de las acciones de la Bolsa de Valores de Nueva York muestran una nueva alza para ese año.  El viernes 18 de septiembre de 1992, el promedio industrial Dow Jones cerró en 3,282 con un fuerte volumen de más de 136 millones de títulos negociados.  Una muestra aleatoria de 120 títulos derterminó que 16 de ellos habían mostrado nuevas alzas anuales ese día.  Usando un nivel de significancia de 0.01, ¿deberíamos concluir que más títulos de los habituales tuvieron nuevas alzas anuales ese día?

\newpage

# Ejercicio 34

¿Cúal es la probabilidad de que estemos rechazando una hipótesis nula verdadera cuando rechazamos el valor hipotético debido a que

a) La estadística de muestra difiere del valor hipotético en más de 2.15 errores estándar en cualquier dirección.

b)El valor del estadístico de la muestra es mayor en más de 1.6 errores estándar.

c) El valor del estadístico de la muestra es menor que el valor hipotético en más de 2.33 errores estándar.  Los distribuidores de fondo de inversión mutua *abiertos* venden acciones adicionales a  los individuos que desean invertir en estos fondos.  Estas acciones están valuadas como *valores de activo neto*, el valor de estos títulos representados por las acciones de los fondos, más una comisión (o cargo) en el intervalo de 0 a 8%.  los fondos *cerrados*, por otra parte, tienen un número fijo de acciones.  Estas acciones se negocian en varias bolsas de valores a precios determinados por el mercado.  Si el precio es mayor que el valor activo neto, se dice que la acción se vende con *prima*: si sucede lo contrario se vende con *descuento*.  Una muestra aleatoria de 15 fondos cerrados el 4 de junio de 1993, encontró los descuentos (valores negativos) y las primas (valores positivos) expresados en porcentajes y enumerados en la tabla MR8-1.  Utilice esta información para responder los ejercicios 35 y 36.

| Tabla MR8-1          | Nombre del título               | Descuento/prima |
|----------------------|---------------------------------|:---------------:|
| Descuentos y primas  | Blue Chip Value                 |       +4.7      |
| para una muesta      | Gabelli Equity Trust            |       -0.7      |
| de 15 fondos         | Liberty All-Star                |       +5.3      |
| mutualistas cerrados | Central Fund of Canada          |       +9.2      |
|                      | Global Health Sciences          |       -0.3      |
|                      | Patriot Global Dividend         |       -0-3      |
|                      | Preferred Income                |       +5.0      |
|                      | Austria Fund                    |       +0.4      |
|                      | Emerging Mexico                 |       -1.9      |
|                      | First Australia                 |       +0.5      |
|                      | Germany Fund                    |       +5.8      |
|                      | Japan Equity                    |       -8.2      |
|                      | Latin America Equity            |       -9.4      |
|                      | Morgan Stanley Emerging Markets |      +10.3      |
|                      | Turkish Investment              |       +1.7      |

\newpage

# Ejercicio 35

¿Se vende significativamente menos fondos de acciones de interés variable con descuentos que con primas? Pruebe a un nivel $\alpha=0.01.$

\newpage

# Ejercicio 36

Un profesor de finanzas desarrolló una teoría que predice que los fondos de acciones de interés variable cerrados se deberían vender con una prima cercana al 5% en promedio.  Suponiendo que la población descuento/prima tiene una distribución aproximadamente normal, ¿apoya la información muestreada esta teoría? Pruebe con $\alpha=0.05.$

\newpage

# Ejercicio 37

Una corredora de bolsa afirma que puede predecir, con el 85% de certeza, el ascenso o caída, durante el mes siguiente, de un valor del mercado de valores.  Para probarlo, predice el resultado de 60 valores y acierta en 45 de sus predicciones ¿Presentan estos datos evidencia concluyente $(con\quad\alpha=0.04)$ de que la exactitud de sus predicciones es significativamente menor que el 85% declarado?

\newpage

# Ejercicio 38

En 1993, el Consejo de Estándares para Contabilidad Financiera (CECF) consideró una propuesta para requerir que las compañías informaran el efecto potencial de la opción de compra de acciones de los empleados sobre los ingresos por acción (IPA).  Una muestra aleatoria de 41 empresas de alta tecnología (AT) reveló que la nueva propuesta reduciría el IPA en un promedio del 13.8%, con una desviación estándar del 18.9%.  Una muestra aleatoria de 35 productores de bienes de consumo (BC) mostró que la propuesta reduciría el IPA en 9.1% en promedio, con desviación estándar del 8.7%.  Con base en estas muestras, ¿es razonable concluir $(para\quad\alpha=0.10)$ que la propuesta de la CECF causaría una mayor reducción en el IPA para las empresas de alta tecnología que para los productores de bienes de consumo?

\newpage

# Ejercicio 39

El 1 de enero de 1996 se tomó una muestra de 32 fondos mutualistas de la bolsa de valores, y se encontró que la tasa promedio de rendimiento anual durante los 30 días anteriores fue del 3,23%, con una desviación estándar de la muestra del 0.51%.  Un año antes, una muestra de 38 fondos mutualistas indicó una tasa promedio de rendimiento del 4.36%, con una desviación estándar de la muestra del 0.84%.  ¿Es razonable llegar a la conclusión (a un nivel$\alpha=0.05)$ de que las tasas de interés del mercado de dinero declinaron durante 1995?

\newpage

# Ejercicio 40

Una organización de crédito y seguros ha desarrollado un nuevo método de alta tecnología para capacitar al nuevo personal de ventas.  La compañía obtuvo una muestra de 16 empleados capacitados de la manera original y encontró ventas diarias promedio de \$688 con desviación estándar de la muestra de \$32.63.  También tomaron una muestra de 11 empleados capacitados con el método nuevo y encontraron un promedio de ventas diarias de \$706 con desviación estándar de la muestra de \$24.84.  Para $\alpha=0.05$, ¿puede la compañía concluir que el promedio diario de ventas aumenta con el nuevo plan?

\newpage

# Ejercicio 41

Los datos de la tabla corresponden a una muestra aleatoria de nueve empresas tomadas de la sección "Digest of Earnings Reports" (Resumen de Informes de Ingresos) del the Wall Street Journal del 6 de febrero de 1992:

a) Encuentre el cambio medio en los ingresos por acción, entre 1991 y 1992.

b) Encuentre la desviación estándar del cambio y la desviación estándar del error de la media.

c) ¿Fueron diferentes los ingresos medios por acción en 1991 y 1992? Pruebe con un nivel $\alpha=0.02.$


| Empresa         | 1    | 2    | 3    | 4    | 5    | 6    | 7    | 8    | 9    |
|-----------------|------|------|------|------|------|------|------|------|------|
| Ingreso de 1991 | 1.38 | 1.26 | 3.64 | 3.50 | 2.47 | 3.21 | 1.05 | 1.98 | 2.72 |
| Ingreso de 1992 | 2.48 | 1.50 | 4.59 | 3.06 | 2.11 | 2.80 | 1.59 | 0.92 | 0.47 |

\newpage
 
# Ejercicio 42

El viernes, aumento el precio (avanzaron) de 11 acciones de una muestra aleatoria de 40 tomada de las 2,500 acciones negociadas en la Bolsa de Valores de Nueva York.  En una muestra tomada el jueves, de 60 acciones de la misma Bolsa, 24 acciones avanzaron.  A un nivel $\alpha=0.10,$ ¿puede llegar a la conclusión de que una proporción menor de las acciones de la Bolsa de Valores avanzaron el viernes con respecto al jueves?

\newpage

# Ejercicio 43

MacroSwift acaba de liberar al mercado un nuevo procesador de textos y la compañía está interesada en determinar si las personas en el grupo de edad 30-39 califican al programa de manera distintas a las del grupo 40-49.  MacroSwift muestreó al azar a 175 personas del grupo 30-39 que compraron el producto  y encontró que 87 calificaron al programa como excelente; de ellos 52 comprarían una actualización.  También muestreó a 220 personas del grupo 40-49 y encontró que 94 calificaron al software como excelente; de ellos 37 comprarían una actualización.  ¿Hay una diferencia significativa en las proporciones de personas en los dos grupos de edad que califican al programa como excelente al nivel $\alpha=0.05$? ¿Es cierto el mismo resultado en cuanto a las proporciones de personas que planean comprar una actualización?

\newpage

# Ejercicio 44

La compañía Ben & Jerry´s Homemade, es una empresa que se dedica a la venta de helados no convencionales, con sabores extravagantes como el de galleta con chispas de chocolate.  En un artículo en The Wall Street Journal se consigna que parte del éxito de la compañía se debe a que atrae a los adultos jóvenes (quienes presumiblemente serán fieles a la compañía durante su periodo pico de consumo de helados).  Suponga que un investigador de mercado lleva a cabo una encuesta a la salida de un supermercado y hace una solo pregunta a 200 compradores consecutivos del helado Ben & Jerry´s y a 200 compradores de la marca competidora de Haagen-Daz de Grand Metropolitan: "¿Tiene usted menos de 25 años?" Si el 7% de los aficionados al helado de Ben & Jerry´s dice "sí" y solamente el 3% de los aficionados al otro helado dice "sí", ¿esto confirma la conclusión del artículo, para 10% de nivel de significancia?

\newpage

# Ejercicio 45

Considere los datos de la tabla que sigue.  En los primeros tres meses 1993, la venta de automóviles de lujo en Estados Unidos disminuyó ligeramente, pero la proporción de automóviles de lujo que fueron importados se incrementó.  Las cifras se muestran en la siguiente tabla. ¿Es significativo el cambio en el porcentanje de mercado de automóviles importados con respecto a los domésticos, al nivel del 5%?

|                                | Ventas de autos de lujo 1992 | Primer trimestre 1993 |
|--------------------------------|:----------------------------:|:---------------------:|
| Porcentaje de autos nacionales |             47.5             |          46.2         |
| Porcentaje de autos importados |             52.5             |          53.8         |
| Total de unidades vendidas     |            373,842           |        372,442        |

\newpage

# Ejercicio 46

En octubre de 1992, una investigación entre 120 macroeconomistas indicó que 87 de ellos creían que la recesión ya había terminado.  Una investigación de 150 agentes de adquisiones encontró que 89 de éstos creían que la recesión ya había terminado.  Al nivel $\alpha=0.10,$ ¿se puede concluir que los agentes de adquisiones eran más pesimistas acerca de la economía de Estados Unidos que los macroeconomistas?

\newpage

# Ejercicio 47

Los largometrajes de animación proporciona grandes ganancias a The Walt Disney Company.  Las películas de éxito, como *Aladdin*, pueden producir ingresos mayores a los 300 millones de dólares después de sus costos de producción.  Pero cada año, además de estos éxitos espectaculares, algunas películas de animación más modestas llegan a las pantallas.  Un analista obtuvo un listado de los ingresos totales (la suma de boletos vendidos) de la primera presentación de todas las películas de animación exhibidas entre 1986 y 1992, los datos reunidos son los siguientes (en millones de dólares):

| Un Cuento Americano                | Universal             | 44.9 |
|------------------------------------|-----------------------|:----:|
| Los Perros Van al Cielo            | MGM/UA                | 26.2 |
| Ferngully: El Bosque Perdido       | Twentieth Century Fox | 20.9 |
| Fievel va al Oeste                 | Universal             | 20.2 |
| Mundo Cool                         | Paramount             | 13.7 |
| Rock-a-Doddle                      | Twentieth Century Fox | 11.6 |
| Bebe´s Kids                        | Paramount             | 7.5  |
| Ositos Cariñositos II              | Columbia              | 5.4  |
| Pinocho y el Emperador de la Noche | New World             | 2.7  |
| Ositos Cariñositos                 | Cineplex              | 2.2  |
| Babar: la Película                 | New Line              | 1.4  |
| Oliver y Compañía                  | Disney                | 52.6 |
| Rescuers Down Under                | Disney                | 27.8 |
| El Gran Ratón Detective            | Disney                | 24,2 |
| Los Rescatadores                   | Disney                | 21.1 |
| Patoaventuras                      | Disney                | 18.1 |

\newpage

# Ejercicio 48

El promedio de Transporte Dow-Jones está basado en los precios de cierre de las acciones comunes de 20 compañías aéreas, ferrocarriles y de fletes.  El 24 de mayo de 1993, el precio promedio de estas 20 acciones disminuyó de \$47.156 a \$47.150 .  Tomando estas acciones como una muestra aleatoria de todas las acciones relacionadas con el transporte, ¿es significativa la disminución observada? Explique su respuesta.


| Acciones                 | Cierre 5/21/93 | Cierre 5/24/93 |
|--------------------------|:--------------:|:--------------:|
| Airborne Freight         |     23.500     |     23.375     |
| Alaska Airlines          |     16.750     |     16.625     |
| American President       |     50.750     |     52.000     |
| AMR                      |     71.625     |     71.875     |
| Burlington Northern      |     53.875     |     54.000     |
| Carolina Freightways     |     13.125     |     13.000     |
| Conrail                  |     51.375     |     51,875     |
| Consolidated Freightways |     15.375     |     15.625     |
| CSX                      |     71.125     |     70.750     |
| Delta Airlines           |     60.250     |     60.750     |
| Federal Express          |     49.750     |     49.375     |
| Norfolk and Southern     |     61.875     |     61.250     |
| Roadway                  |     54.750     |     55.000     |
| Ryder System             |     27.250     |     27.125     |
|  Santa Fe Pacific        |     16.750     |     17.000     |
| Southwest Airline        |     40.375     |     40.500     |
| UAL                      |     138.750    |     138.750    |
| Union Pacific            |     63.250     |     63.000     |
| USAir Group              |     22.500     |     22.625     |
| XTRA                     |     40.125     |     38.500     |
| Average Price            |     47.156     |     47.150     |

\newpage

# Ejercicio 49

En un estudio económico se trata de determinar si los proyectos industriales textiles generan un mayor empleo que los proyectos en industrias de manufacturas de muebles.

Una muestra tomada de 16 industrias textiles, indicó que los nuevos empleos por cada millón de bolívares de inversión fueron 400, con desviación típica de 20.  En una muestra de 14 industrias de muebles se generaron 380 empleos por cada millón de bolívares invertidos, con desviación típica de 18.  Suponiendo $\sigma^2_x=\sigma^2_y=\sigma^2$ el estudio concluyó que los proyectos textiles generaban un 6% más de empleos que los otros.  ¿Se justifica la conclusión? ¿Podría ser rechazada la hipótesis de igualdad de la creación media de empleos con $\sigma=0.05$?

\newpage

# Ejercicio 50

Se desea saber si los mercados de Maracaibo y Caracas son iguales respecto al precio que los consumidores están dispuestos a pagar por un cierto producto.  Suponga las varianzas iguales.  Una muestra de 10 consumidores en Maracaibo dio un precio medio de Bs. 5, con una desviación típica de Bs. 2; en Caracas una muestra de 15 consumidores dio un precio medio de Bs. 5,50, con una desviación típica de Bs. 2,10. $\alpha=0,05.$

\newpage

# Ejercicio 51

En una ciudad se escogió una muestra aleatoria de 121 personas para preguntarles el precio que estarían dispuestas a pagar por un determinado artículo, dando una media de Bs. 5,50, con una desviación típica de Bs. 0,50.  En otra ciudad una muestra de 61 personas dio una media de Bs. 5, con una desviación típica de Bs. 0,37. ¿Hay diferencia significativa en las varianzas de los precios? $\alpha=o,05.$

\newpage

# Ejercicio 52

Los siguientes datos corresponden a la clasificación de empresas vendedoras de un mismo producto según dos criterios: El área de la zona metropolitana en que están ubicadas, y el volumen de ventas con relación al promedio de éstas:

|  | Sabana Grande | Centro | Otras zonas | Total |
|---------------------------------|:-------------:|:------:|:-----------:|:-----:|
| Ventas menores que  el promedio | 58 | 46 | 38 | 142 |
| Ventas en el promedio | 102 | 160 | 84 | 346 |
| Ventas mayores que el promedio | 34 | 51 | 60 | 145 |
| Total | 194 | 257 | 182 | 633 |

a) ¿Según estos datos se podría decir que  la ubicación influye en el volumen de ventas? $\alpha=0.05.$ Calcular el coeficiente de contigencia.

