---
title: "Ejercicios 2"
author: "Yoselin Arvelaiz"
date: "26 de febrero de 2018"
output: pdf_document
---

## Ejercicio 12.

Una agencia de rentas, que alquila equipo pesado por día, ha encontrado que, en promedio, se renta una costosa máquina sólo un día de cada cinco. Si la renta en un día es independiente de la renta en cualquier otro día, encuentre la distribución de probabilidad de $Y$, el número de días entre un par de rentas. 

**\underline{Solución:}**

Sea $Y$ el número de días entre un par de renta.

Según el enunciado tenemos que el promedio una renta de la costosa maquina es un día de cada cinco días, por lo tanto la probabilidad de que se rente la maquina es $p=\displaystyle \frac{1}{5}=0.2$, de este modo tenemos que la probabilidad de que no ocurra una renta en un día cualquiera es $1-p=1-0.2=0.8$.

Podemos pensar estas probabilidades en base a la distribución Geometrica, donde los eventos entre evento son los fracasos y cuando se consigue alquilar la maquina es el éxito. Entonces la probabilidad de que halla un dia entre dos rentas, está dado por, 

$$P(Y=1)=(0.8)(0.2)$$

De que hallan dos días

$$P(Y=2)=(0.8)^2(0.2)$$

Así sucesivamente, Por lo que, la distribución de probabilidad de $Y$ es una distribución geométrica que está dada por,

$$P(Y=y)=(0.8)^y(0.2)$$

para $y=0,1,2,...$

\newpage

## Ejercicio 13.

Una compañia de seguros expide una póliza de un año por $\$1000$ dólares contra el suceso $A$ que históricamente le ocurre a 2 de cada 100 propietarios de la póliza. Las tarifas administrativas son de $\$15$ por póliza y no son parte de la "utilidad" de la compañia. ¿Cuánto debe cobrar la compañia por póliza si requiere que la utilidad esperada por póliza sea de $\$50$? [Sugerencia: si $C$ es la prima por la póliza, la "utilidad" de la compañia es $C-15$ si $A$ no ocurre y $C-15-1000$ si $A$ ocurre.]

**\underline{Solución:}**

Sea 

$$U=\left\{
\begin{matrix}
C-15-1000 & si & \text{A  ocurre}\\
C-15 & si & \text{A no ocurre}
\end{matrix}
\right .$$

la variable aleatoria "utilidad", tenemos por otro lado que, 

$P(A)=\displaystyle \frac{2}{100}=0.02$

$P(A^c)=0.98$

Se requiere que la utilidad esperada por póliza sea de $\$50$, por lo que, $$\mathbb{E}(U)=50$$

Asi usando la definición del valor esperado, tenemos:

$$\mathbb{E}(U)= (C-15)P(A) + (C-15-1000)P(A^2)=50$$

Sustituyendo nos queda, 

$$\mathbb{E}(U)=(C-15)0.02 + (C-15-1000)0.98=50$$

Despejando el valor de $C$, se obtiene,

$$C=85$$

Esto significa que la compañia debe cobrar $\$85$ por póliza para que la utilidad por póliza sea de $\$50$.

\newpage

## Ejercicio 14.

Un cliente potencial para una póliza de seguro contra incendio por $\$85,000$ es propietario de una casa en una zona que, de acuerdo con la experiencia, puede sostener una pérdida total en un año determinado con probabilidad de $.001$ y un $50\%$ de pérdida con probabilidad de $.01$. Si se ignoran todas las otrás pérdidas parciales, ¿qué prima debe cobrar la compañia de seguros por una póliza anual para que no haya pérdida ni ganancia en todas las pólizas de $\$85,000$ en esta zona?

**\underline{Solución:}**

Sea $Y=$ pérdidas de una póliza de seguro de \$85.000 para cada cliente, donde, 

$$Y=\left\{
\begin{matrix}
85.000 & \text{con probabilidad} & 0.001\\
42.500 & \text{con probabilidad} & 0.01
\end{matrix}
\right .$$


Luego, la pérdida y ganancia de una compañia está dada por $C-Y$. Sí, $\mathbb{E}(C-Y)=0$ entonces $\mathbb{E}(Y)=C$

Así, usando la definición del valor esperado, tenemos que, 

$$C=\mathbb{E}(Y)= 85000(0.001)+42500(0.01)=510$$

La prima que debe cobrar la compañia de seguros es de $\$510$ por una póliza anual para que no haya pérdida ni ganancia en todas las pólizas en esta zona.

\newpage

## Ejercicio 15.

El gerente del almacén de una fábrica ha construido la siguiente distribución de probabilidad para la demanda diaria (número de veces que se usa) de una herramienta en particular.

\begin{center}
\begin{tabular}{c|c c r}
$y$ & 0 & 1 & 2 \\ \hline
$p(y)$ & .1 & .5 & .4 \\
\end{tabular}
\end{center}

Cuesta a la fábrica \$10 cada vez que la herramienta se usa. Encuentre la media y la varianza del costo diario por usar la herramienta.

\textbf{\underline{Solución:}}

Sabiendo que cada vez que la herramienta se usa tiene un costo de \$10, definamos $X=10Y$, donde:

$$X=\left\{
\begin{matrix}
0 & \text{para} & Y=0\\
10 & \text{para} & Y=1\\
20 & \text{para} & Y=2
\end{matrix}
\right .$$

Usando la definición del valor esperado, tenemos,

$$\mu=\mathbb{E}(X)=\sum_{i=1}^3 x_i P(X=x_i)=0(0.1)+10(0.5)+20(0.4)=13$$

Luego,

$$\mathbb{E}(X^2)=\sum_{i=1}^3 x_i^2 P(X=x_i)=0(0.1)+100(0.5)+400(0.4)=210$$

Tenemos que la varianza está dada por,

$$\sigma^2=\mathbb{E}[(X-\mu)^2]=\mathbb{E}(X^2)-\mu^2=210-(13)^2=41$$

\newpage

## Ejercicio 16.

Un inversionista está pensando en comprar un número muy grande de acciones de una compañia. La cotización de las acciones de la bolsa, durante los seis meses anteriores, es de gran interés para el inversionista. Con base en esta información, se observa que la cotización se relaciona con el producto nacional bruto. Si el PNB aumenta, la probabilidad de que el valor de las acciones aumente es de 0.8. Si el PNB es el mismo, la probabilidad de que las acciones aumenten su valor es de 0.2. Si el PNB disminuye, la probabilidad es de sólo 0.1. Si para los siguientes seis meses se asignan las probabilidades 0.4, 0.3 y 0.3 a los eventos, el PNB aumenta,es el mismo y disminuye, respectivamente, determinar la probabilidad de que las acciones aumenten su valor en los próximos seis meses.


\textbf{\underline{Solución:}}

Sea $A$ el evento "las acciones aumentan su valor" y los eventos $B_1,B_2$ y $B_3$, el PNB aumenta, el PNB es el mismo y el PNB disminuye, respectivamente. Luego, como los eventos $B_1,B_2$ y $B_3$ son disjuntos, tenemos, 

$$P(A)=  P(A\cap B_1)+P(A\cap B_2)+P(A\cap B_3)$$

Pero por probabilidad condicional,

$$P(A)=P(B_1)P(A|B_1)+P(B_2)P(A|B_2)+P(B_3)P(A|B_3)$$

Donde se conocen, $P(B_1)=0.4$ , $P(A|B_1)=0.8$ , $P(B_2)=0.3$ , $P(A|B_2)=0.2$ ,$P(B_3)=0.3$ , $P(A|B_3)=0.1$ ; sustituyendo,

$$
\begin{array}{rl}
P(A)&=P(B_1)P(A|B_1)+P(B_2)P(A|B_2)+P(B_3)P(A|B_3)\\
&=0.4(0.8)+0.3(0.2)+0.3(0.1)\\
&=0.41\\
\end{array}
$$

La probabilidad de que las acciones aumenten su valor en los próximos seis meses es de 0.41.

\newpage

## Ejercicio 17.

Una compañia de seguros debe determinar la cuota anual a cobrarse por un seguro de \$50 mil para hombres cuya edad se encuentra entre los 30 y 35 años. Con base en las tablas actuariales el número de fallecimientos al año, para este grupo, es de 5 por cada mil. Si $X$ es la variable aleatoria que representa la ganancia de la compañia de seguros, determinar el monto de la cuota anual para que la compañia no pierda, a pesar de tener un número grande de tales seguros.

\textbf{\underline{Solución:}}

El seguro cubre a los hombres durante cinco años por un monto de \$50 mil. Anualmente el número de fallecimientos es de 5 por cada mil, representando un 0.5\% de fallecidos anual. Luego, la pérdida y ganancia está dado por, $C-X$, donde $C$ es la cuota anual. 
 
Si $\mathbb{E}(C-X)=0$ entonces $\mathbb{E}(X)=C$. entonces, $$C=(50000)(0.005)=250$$

\newpage

## Ejercicio 18.

1. Dadas las probabilidades condicional en la tabla siguiente y las no condicionales $P(Y=1)=0.3$ y $P(Y=2)=0.7$, ¿cuál es el valor esperado de X?

\begin{table}[htpb]
\begin{center}
\begin{tabular}{l c r}
\hline 
 $x_i$ & $P(x_i|Y=1)$ & $P(x_i|Y=2)$ \\
\hline \hline
0 & 0.2 & 0.1 \\
5 & 0.4 & 0.8  \\
10 & 0.4 & 0.1 \\ \hline
\end{tabular}
\end{center}
\end{table}

\begin{itemize}
\item[A.] 5.0
\item[B.] 5.3
\item[C.] 5.7
\end{itemize}

\textbf{\underline{Solución:}}

La respuesta correcta es la $B$, ya que

$$\mathbb{E}(X|Y=1)=\sum_{x=1}^{3}x_i P(x_i|Y=1)=0(0.2)+5(0.4)+10(0.4)=6$$ y 

$$\mathbb{E}(X|Y=2)=\sum_{x=1}^{3}x_i P(x_i|Y=2)=0(0.1)+5(0.8)+10(0.1)=5$$

Por lo que, $$\mathbb{E}(X)=6(0.3)+5(0.7)=5.3$$

----

Use los siguientes datos para responder las preguntas 2 hasta la 6.

\begin{center}
\begin{tabular}{l c c r}
\hline 
& & Probabilidad Conjunta & \\
Rentas & $R_B$=0.5 & $R_B$=0.2 & $R_B$=-0.3 \\ \hline
$R_A$=-0.1 & 0.4 & 0 & 0\\
$R_A$=0.1 & 0 & 0.3 & 0\\
$R_A$=0.3 & 0 & 0 & 0.3\\
\end{tabular}
\end{center}

2. Dada la tabla de probabilidades, el valor esperado de la rentabilidad del valor A está cercano a:

\begin{itemize}
\item[A.] 0.08
\item[B.] 0.12
\item[C.] 0.15
\end{itemize}

\textbf{\underline{Solución:}}

 La respuesta correcta es la opción A., ya que el valor esperado del valor A es $(-0.1)(0.4)+(0.1)(0.3)+(0.3)(0.3)=0.08$

3. La desviación estándar del valor B es cercano a:

\begin{itemize}
\item[A.] 0.11
\item[B.] 0.22
\item[C.] 0.33
\end{itemize}

\textbf{\underline{Solución:}}

La respuesta correcta es la C., ya que, el valor esperado de la rentabilidad del valor de B, $R_B =\{0.5,0.2,-0.3\}$ es

$$
\begin{array}{rl}
\mathbb{E}(R_B) &= \sum_{i=1}^{3}R_{B_i}P(R_{B_i}|R_{A_i})\\
&=(0.5)(0.4)+(0.2)(0.3)+(-0.3)(0.3)\\
\mathbb{E}(R_B) &=0.17
\end{array}
$$ 

La varianza esta dada por

$$
\begin{array}{rl}
Var(R_B) &= \mathbb E[(R_B-\mathbb E[R_B])^2]\\
&= \sum_{i=1}^{3} P(R_{B_i}|R_{A_i}) (R_{B_i}-\mathbb{E}[R_{B_i}])^2\\
&=(0.4)(0.5-0.17)^2+(0.3)(0.2-0.17)^2+(0.3)(-0.3-0.17)^2\\
Var(R_B)&=0.1101
\end{array}
$$

y la desviación estándar $\sigma=\sqrt{Var(R_b)}=\sqrt{0.1101}=0.33$

4. La varianza del valor A es cercano a:

\begin{itemize}
\item[A.] 0.03
\item[B.] 0.12
\item[C.] 0.17
\end{itemize}

\textbf{\underline{Solución:}}

La varianza de la rentabilidad del valor de A es $(0.4)(-0.1-0.08)^2+(0.3)(0.1-0.08)^2+(0.3)(0.3-0.08)^2=0.0276$. La respuesta es la opción A.

5. La covarianza entre los valores A y B es cercano a:

\begin{itemize}
\item[A.] -0.160
\item[B.] -0.055
\item[C.] 0.004
\end{itemize}

\textbf{\underline{Solución:}}

$$
\begin{array}{rl}
Cov(R_A,R_B) &= \displaystyle \sum_{i=1}^{3}P(R_{A_i},R_{B_i})(R_{A_i}-\mathbb{E}[R_A])(R_{B_i}-\mathbb{E}[R_B])\\
& = (0.4)(-0.1-0.08)(0.5-0.17)+(0.3)(0.1-0.08)(0.2-0.17)+(0.3)(0.3-0.08)(-0.3-0.17)\\
Cov(R_A,R_B) & =-0.0546
\end{array}
$$

La respuesta es la B.

6. Las correlaciones entre $R_A$ y $R_B$ es cercano a:

\begin{itemize}
\item[A.] -0.99
\item[B.] 0.02
\item[C.] 0.86
\end{itemize}

\textbf{\underline{Solución:}}

$$
\begin{array}{rl}
Corr(R_A,R_B) &=\displaystyle \frac{Cov(R_A,R_B)}{\sigma_{R_A}\sigma_{R_B}}\\
&=\displaystyle \frac{-0.0546}{0.33(0.17)}\\
Corr(R_A,R_B)&=-0.9907
\end{array}
$$
La respuesta es la A.

7. La probabilidad que DJIA aumente mañana es de  2/3. La probabilidad de un aumento en el DJIA declarado como probabilidades es:

\begin{itemize}
\item[A.] Dos a uno.
\item[B.] Uno a tres.
\item[C.] Dos a tres.
\end{itemize}

\textbf{\underline{Solución:}}

Sea $X=$ DJIA aumenta mañana.

Se tiene que $P(X)= \displaystyle \frac{2}{3}$ . 

Las probabilidades que los eventos ocurran son $\displaystyle \frac{P(X)}{1-P(X)}=\displaystyle \frac{2/3}{1-2/3}=2/1$ que es igual a dos a uno. La respuesta es la A.

8. Una distribución uniforme discreta (cada evento tiene igual probabilidad de ocurrencia) tiene los siguientes posibles resultados para $X={1,2,3,4}$. La varianza de esta distribución es cercana a:

\begin{itemize}
\item[A.] 1.00
\item[B.] 1.25
\item[C.] 2.00
\end{itemize}

\textbf{\underline{Solución:}}
 
La respuesta correcta es la B. El valor esperado de $X$ es

$$\mathbb{E}(X)=\sum_{x=1}^{4}x P(X=x)=(1+2+3+4)(1/4)=2.5$$

La varianza es 

$$Var(X)=\sum_{x=1}^{4} (x-\mathbb{E}[X])^2 P(X=x)=[(1-2.5)^2+(2-2.5)^2+(3-2.5)^2+(4-2.5)^2)](1/4)=1.25$$

9. Si los eventos A y B son mutuamente exclusivos, entonces, 

\begin{itemize}
\item[A.] $P(A|B)=P(A)$
\item[B.] $P(AB)=P(A)P(B)$
\item[C.] $P(A\cup B)=P(A) + P(B)$
\end{itemize}

\textbf{\underline{Solución:}}

La respuesta correcta es la opción C. Ya que $P(AB)=P(A)P(B)$ sí los eventos son independientes y cómo los eventos son mutuamente exclusivos, ambos no pueden ocurrir así que tanto $P(A|B)$ como $P(AB)$ pueden ser cero.

10. En una bola de caridad, 800 nombres son introducidos. Cuatro de los nombres son idénticos. En una extracción aleatoria, ¿cuál es la probabilidad de que uno de estos cuatro nombres sea extraido?

\begin{itemize}
\item[A.] 0.004
\item[B.] 0.005
\item[C.] 0.010
\end{itemize}

\textbf{\underline{Solución:}}

Sean $n_1,n_2,n_3$ y $n_4$ los cuatro nombres idénticos, entonces, la probabilidad de que alguno de estos nombres sea escogido es

$$P(n_1\cup n_2\cup n_3\cup n_4)=1/800+1/800+1/800+1/800=0.005$$

La respuesta correcta es la B.

11. Casi 900 contribuyentes con ingresos por debajo de  \$100000, 35 fueron auditados por IRS. La probabilidad de que un individuo escogido al azar con ingreso por debajo de \$100000 fuese auditado es cercano a:

\begin{itemize}
\item[A.] 0.039
\item[B.] 0.125
\item[C.] 0.350
\end{itemize}

\textbf{\underline{Solución:}}

900 contribuyentes tienen ingresos por debajo de \$100000 y 35 sólo fueron auditados por IRS, por lo que la probabilidad de escoger un individuo al azar de 900 contribuyente es $\displaystyle \frac{35}{900}=0.03888889$. La respuesta es la A.

12. ¿cuáles de los siguientes valores no puede ser la probabilidad de un evento?

\begin{itemize}
\item[A.] 0.000
\item[B.] 1.00
\item[C.] 1.25
\end{itemize}

\textbf{\underline{Solución:}}

La respuesta es la C, ya que el rango de la probabilidad es de 0 hasta 1. 

13. Dos eventos mutuamente exclusivos:

\begin{itemize}
\item[A.] Siempre ocurren ambos.
\item[B.] No puede ocurrir ambos.
\item[C.] Pueden algunas veces ocurrir ambos.
\end{itemize}

\textbf{\underline{Solución:}}

La respuesta es la B. Puede ocurrir uno de los dos pero no ambos.

\newpage

## Ejercicio 19.

1. Dados los siguientes datos de probabilidad para la rentabilidad del mercado y la rentabilidad del mejor petróleo, calcule la covarianza de la rentabilidad entre el mercado y el mejor petróleo.

\begin{center}
\begin{tabular}{l c c r}
\hline 
& $R_p$=20\% & $R_p$=10\% & $R_p$=5\% \\ \hline
$R_m$=15\% & 0.4 & 0 & 0\\
$R_m$=10\% & 0 & 0.2 & 0\\
$R_m$=0\% & 0 & 0 & 0.4\\
\end{tabular}
\end{center}

\textbf{\underline{Solución:}}

Calcularemos primeramente el valor esperado a cada rentabilidad,

$$\mathbb{E}(R_p)=0.4(0.05)+0.2(0.10)+0.4(0.20)=0.12$$ y

$$\mathbb{E}(R_m)=0.4(0.0)+0.2(0.10)+0.4(0.15)=0.08$$
La covarianza esta dada por,

$$Cov(R_p,R_m)=\sum_{i=1}^3 P(R_{p_i},R_{m_i})(R_{p_i}-\mathbb{E}[R_p])(R_{m_i}-\mathbb{E}[R_m])$$ Asi,

$$
\begin{array}{rl}
Cov(R_p,R_m) &= 0.4(0.05-0.12)(0.0-0.08)+0.2(0.10-0.12)(0.10-0.08)+0.4(0.20-0.12)(0.15-0.08) \\
&=0.4(-0.07)(-0.08)+0.2(-0.02)(0.02)+0.4(0.08)(0.07)\\
Cov(R_p,R_m) &=0.0044
\end{array}
$$

Por lo que la covarianza de ambas rentabilidades es de 0.0044.

2. La correlación de rentabilidades de la rentabilidad de Productos Cape y de la Industria Dogger es de 0.6. La desviación estándar de rentabilidad de los productos Cape es de 15\% y de los Dogger es de 20\%.La rentabilidad esperada para Dogger es de 18\%, y la rentabilidad esperada para Cape es de 12\%. Calcular la rentabilidad esperada y la desviación estándar de una carpeta que tiene \$300000 invertidos en Dogger y \$200000 invertidos en Cape.

\textbf{\underline{Solución:}}

Los pesos de la carpeta para Dogger y Cape, estan dados por,

$$w_D=\displaystyle \frac{300000}{300000+200000}=\displaystyle \frac{300000}{500000}=0.6$$ 

y

$$w_C= \displaystyle \frac{200000}{300000+200000}=\displaystyle \frac{200000}{500000}=0.4$$

EL valor esperado de la rentabilidad de la carpeta, viene dado,

$$\mathbb{E}(R_{car})=w_D\mathbb{E}(R_D)+w_C\mathbb{E}(R_C)$$ 

Donde $\mathbb{E}(R_D)=0.18$ y $\mathbb{E}(R_C)=0.12$, sustituyendo,

$$
\begin{array}{rl}
\mathbb{E}(R_{car})&=0.6(0.18)+0.4(0.12)\\
\mathbb{E}(R_{car})&=0.156
\end{array}
$$

La rentabilidad esperada es de 15.6\%. 

Calculemos ahora la desviación estándar de la rentabilidad de la carpeta,

La varianza de la carpeta está dada por, 

$$Var(R_{car})=w_D^2\sigma^2_{R_D}+w_C^2\sigma^2_{R_C}+2w_Dw_CCov(R_D,R_C)$$

esto es equivalente a,

$$Var(R_{car})=w_D^2\sigma^2_{R_D}+w_C^2\sigma^2_{R_C}+2w_Dw_C\sigma_{R_D}\sigma_{R_C}\rho(R_D,R_C)$$

donde conocemos lo siguiente, $\sigma_{R_D}=0.20$, $\sigma_{R_C}=0.15$ y $\rho(R_D,R_C)=0.6$

$$
\begin{array}{rl}
Var(R_{car})&=(0.6)^2(0.20)^2+(0.4)^2(0.15)^2+2(0.6)(0.4)(0.20)(0.15)(0.6)\\
Var(R_{car})&=0.02664\\
\end{array}
$$

La desviación estándar de la rentabilidad de la carpeta es $\sigma_{R_{car}}=\sqrt{0.02664}=0.1632$, que representa un 16.32\% de desviación.

3. M. Atwood, un analísta, ha desarrollado un sistema de puntaje para bonos y descubrió que si el puntaje de un bono es menor que 20, hay un 85\% de probabilidad de que incumpla dentro de cinco años. Si el puntaje del bono es mayor o igual a 20, hay sólo un 40\% de probabilidad que incumpla dentro de cinco años. Dado que una opción elegida al azar actualmente tiene un 25\% de probabilidad de una puntuación menor a 20, ¿cuál es la probabilidad de que un bono que incumpla en los próximos cinco años tenga un puntaje de 20 o superior?

\textbf{\underline{Solución:}}

Sea $A$ un evento "puntaje del bono menor que 20" y sea $B$ el evento "incumple dentro de cinco años". Así, tenemos lo siguiente, 

$P(A)=0.25$, $P(A^c)=0.75$, $P(B|A)=0.85$ y $P(B|A^c)=0.40$

Usando el teorema de Bayes, obtenemos lo siguiente,

$$P(A^c|B)=\frac{P(A^c)P(B|A^c)}{P(A^c)P(B|A^c)+P(A)P(B|A)}$$

$$
\begin{array}{rl}
P(A^c|B) &=\displaystyle  \frac{0.75(0.40)}{0.75(0.40)+0.25(0.85)}\\
&=\displaystyle \frac{0.3}{0.5125}\\
P(A^c|B) &=0.5853
\end{array}
$$

Esto significa que si el bono incumple en los próximos cinco años hay un 58.53\% de probabilidad de que el bono tenga un puntaje de 20 o superior.

4. Un bono  que vence en un año tiene un precio de \$950 hoy. Estima que tiene una probabilidad de 10\% de incumplimiento. Si el bono incumple, espera recuperar \$600. Si no lo hace por defecto, pagará \$1,080 al vencimiento. La tasa nominal libre de riesgo de un año es de 7.5\%.

\begin{itemize}
\item[A.] ¿Cuáles son las probabilidades de incumplimiento de este bono?
\item[B.] ¿Cuál es el beneficio esperado del bono en un año?
\item[C.] ¿Cuál es la rentabilidad esperada de un bono?
\item[D.] ¿Cuál podría ser el precio del bono si la rentabilidad esperada fuera igual a la tasa libre de riesgo?
\end{itemize}


\textbf{\underline{Solución:}}

A. Las probabilidades de incumplimiento del bono son, $\displaystyle \frac{0.10}{1-0.10}=\displaystyle \frac{1}{9}$ 

B. El beneficio esperado del bono en un año es, 

Sea $B$ el evento del beneficio del bono, y sea $C$ el evento de incumplimiento, entonces, 

$$\mathbb{E}(B)=P(C)(600)+P(C^c)(1080)$$
donde $P(C)=\displaystyle \frac{1}{9}=0.1$, sustituyendo,

$$\mathbb{E}(B)=(0.1)(600)+(0.9)(1080)=1032$$

El beneficio esperado del bono en un año es de \$1,032.

C. La rentabilidad esperada es, $\displaystyle \frac{1032}{950}-1=0.0863$, que representa el 8.63\% de rentabilidad.

D. Si $\displaystyle \frac{1032}{\text{precio}}-1=0.075$ entonces $\text{precio}=\displaystyle \frac{1032}{0.075+1}=960$, el precio sería de \$960.


5. Considere una carpeta de tres valores: 

\begin{itemize}
\item[Valor A] (55\% de la carpeta) tiene una rentabilidad esperada de 8\%, con una desviación estándar de  24\%. 
\item[Valor B] (25\% de la carpeta) tiene una rentabilidad esperada de 4\%, con una desviación estándar de  18\%. 
\item[Valor C] (20\% de la carpeta) tiene una rentabilidad esperada de 3\%, con una desviación estándar de  15\%. 
\end{itemize}

Las correlaciones entre la rentabilidad de valores son, 


\begin{itemize}
\item[Valor A] con valor B: 0.85
\item[Valor A] con valor C: 0.30
\item[Valor B] con valor C: -0.15
\end{itemize}

\begin{itemize}
\item[A.] En base a estos datos, construya una matriz de covarianza para los tres valores de rentabilidad de la carpeta.
\item[B.] Calcule la rentabilidad esperada y la desviación estándar de la carpeta.
\item[C.] Proporcione un conjunto de tres eventos mutuamente excluyentes y exhaustivos con respecto a la relación entre la rentabilidad realizada de la carpeta y su respectiva rentabilidad.
\item[D.] Si le añade tres valores a la carpeta, ¿cuántas varianzas y únicas covarianzas necesitará para calcular la varianza de la carpeta?.
\end{itemize}

\textbf{\underline{Solución:}}

A. Primero, calculemos las varianzas de los valores A,B y C. 

$$Var(A)=(0.24)^2=0.0576$$ $$Var(B)=(0.18)^2=0.0324$$ $$Var(C)=(0.15)^2=0.0225$$

Ahora calculemos las covarianzas de los tres valores, 

$$Corr(A,B)=\frac{Cov(A,B)}{\sigma_A\sigma_B}$$
Por lo que, $Cov(A,B)=\rho(A,B)\sigma_A\sigma_B$. Así, tenemos lo siguiente, 

$$Cov(A,B)=(0.85)(0.24)(0.18)=0.0367$$

$$Cov(A,C)=(0.30)(0.24)(0.15)=0.0108$$ 

$$Cov(B,C)=(-0.15)(0.18)(0.15)=-0.0041$$

La matrix de covarianza es la siguiente, 

\begin{table}[htpb]
\begin{center}
\begin{tabular}{|l| c c r|}
\hline 
& Valor A & Valor B & Valor C \\
\hline \hline
Valor A & 0.0576 & 0.0367 & 0.0108 \\
Valor B & 0.0367 & 0.0324 & -0.0041 \\
Valor C & 0.0108 & -0.0041 & 0.0225 \\ \hline
\end{tabular}
\end{center}
\end{table}


B. Calculemos primero la rentabilidad esperada, donde los pesos de la carpeta para los valores A, B y C, son 

$w_A=0.55$, $w_B=0.25$ y $w_C=0.20$. Así, el valor esperado esta dado por, 

$$\mathbb{E}(R_c)=w_A\mathbb{E}(R_A)+w_B\mathbb{E}(R_B)+w_C\mathbb{E}(R_C)$$

$$\mathbb{E}(R_c)=(0.55)(0.08)+(0.25)(0.04)+(0.20)(0.03)=0.06$$
Ahora, calculemos la varianza que esta dada por, 

$$Var(R_c)=w_A^2\sigma^2_{A}+w_B^2\sigma^2_{B} + w_C^2\sigma^2_C+2w_Aw_BCov(A,B)+2w_Aw_CCov(A,C)+2w_Bw_CCov(B,C)$$
Sustituyendo nos queda lo siguiente,

$$
\begin{array}{rl}
Var(R_c)&=(0.55)^2(0.0576)+(0.25)^2(0.0324) + (0.20)^2(0.0225)\\
& +2(0.55)(0.25)(0.0367)+2(0.55)(0.20)(0.0108)\\
&+2(0.25)(0.20)(-0.0041)\\
&=0.0324\\
\end{array}
$$

La desviación estándar de la carpeta es $\sqrt{0.0324}=0.18$, representando el 18\% de desviación.

C. Los eventos pueden ser, 

\begin{itemize}
\item[Evento 1:] La rentabilidad realizada es mayor que la rentabilidad esperada.
\item[Evento 2:] La rentabilidad realizada es igual que la rentabilidad esperada.
\item[Evento 3:] La rentabilidad realizada es menor que la rentabilidad esperada.
\end{itemize}


D. Si le añadimos tres valores a la carpeta, la carpeta tendrá seis valores, las cuales se calcularían seis varianzas, y se calcularián quince únicas covarianzas para calcular la varianza de la carpeta.

6. Usted está pronosticando las ventas de un proveedor de materiales de construcción mediante la evaluación de los planes de expansión de su cliente más grande, un constructor de viviendas. Se estima que la probabilidad de que el cliente aumente sus pedidos de materiales de construcción es de 25\%. Si el cliente incrementa sus pedido, la probabilidad que el constructor de vivienda comience una nueva construcción es de 70\%. Si el cliente no aumenta sus pedidos desde un proveedor, hay sólo un 20\% de probabilidad de que el constructor inicie la edificación. Más tarde, descubres que el constructor iniciará la nueva construcción. Debido a esta información, ¿cuál es su probabilidad nueva (actualizada) de que el cliente aumente sus pedidos desde un proveedor ? 

\textbf{\underline{Solución:}}

Sea $A$ el evento "comienza una nueva construcción" y $B$ el evento "incrementa sus pedidos desde un proveedor", entonces tenemos la siguiente información, 

$P(B)=0.25$, $P(A|B)=0.70$ y $P(A|B^c)=0.20$. Entonces, usando el teorema de Bayes, tenemos lo siguiente, 

$$
\begin{array}{rl}
P(B|A) & =\displaystyle \frac{P(B)P(A|B)}{P(B)P(A|B)+P(B^c)P(A|B^c)}\\
& = \displaystyle  \frac{0.25(0.70)}{0.25(0.70)+0.75(0.20)}\\
&=\displaystyle \frac{0.175}{0.325}\\
P(B|A) &=0.538
\end{array}
$$

En base a la nueva información la probabilidad de que el cliente aumente sus pedidos a un proveedor es de 53.8\%.
