---
title: "Ejercicios de Intervalos de Confianza"
subtitle: "Diplomado de Probabilidad y Estadística Matemática en R"
author: "http://synergy.vision/"
output:
  pdf_document:
      toc: yes
      toc_depth: 4
      includes:
        in_header: ./preambulo.tex
  html_document: default
fontsize: 12pt
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

\newpage

# Ejercicio 1

Una muestra aleatoria simple es una muestra dibujada de una manera que cada miembro de la población tiene:

A. alguna posibilidad de ser seleccionado en la muestra.

B. una posibilidad igual de ser incluido en la muestra.

C. un 1% de posibilidades de ser incluido en la muestra.

\newpage

# Ejercicio 2

El error de muestreo se define como:

A. un error que ocurre cuando se dibuja una muestra de menos de 30 elementos.

B. un error que ocurre durante la recopilación, grabación y tabulación de datos.

C. la diferencia entre el valor de una muestra estática y el valor del parámetro de población correspondiente

\newpage

# Ejercicio 3

La edad promedio de todos los candidatos CFA es de 28 años. La edad media de una muestra aleatoria de 100 candidatos llamados es de 26.5 años. La diferencia de 1.5 años se llama:

A. error aleatorio.

B. error de muestreo.

C. error poblacional.

\newpage

# Ejercicio 4

Si n es grande y la desviación estándar de la población es desconocida, el error estándar de la distribución muestral de la media muestral es **igual** a:

A. Desviación estándar de la muestra dividida por el tamaño de la muestra.

B. Desviación estándar de la población multiplicada por el tamaño de la muestra.

C. muestra la desviación estándar dividida por la raíz cuadrada del tamaño de la muestra.

\newpage

# Ejercicio 5

El error estándar de la distribución muestral de la media muestral para un tamaño de muestra de **n** extraído de una población con una media de $\mu$ y una desviación estándar de $\sigma$ es:

A. Desviación estándar de la muestra dividida por el tamaño de la muestra.

B. muestra la desviación estándar dividida por la raíz cuadrada del tamaño de la muestra.

C. Desviación estándar poblacional dividida por la raíz cuadrada del tamaño de la muestra.

\newpage

# Ejercicio 6

Para aplicar el teorema del límite central a la distribución muestral de la media muestral, la muestra generalmente se considera grande si **n** es mayor que:

A. 20.

B. 25.

c. 30.

\newpage

# Ejercicio 7

Suponga que una población tiene una media de 14 con una desviación estándar de 2. Si se extrae una muestra aleatoria de 49 observaciones de esta población, el error estándar de la media de la muestra está cerrado a:

A. 0.04.

B. 0.29.

C. 2.00.

\newpage

# Ejercicio 8

La media de la población es 30 y la media de una muestra de tamaño 100 es 28.5. La varianza de la muestra es 25. El error estándar de la media muestral es el más cercano a:

A. 0.05.

B. 0.25.

C. 0.50.

\newpage

# Ejercicio 9

Una muestra aleatoria de 100 clientes de computadoras consumió un promedio de \$75 en la tienda. Suponiendo que la distribución es normal y la desviación estándar de la población es de \$20, el intervalo de confianza del 95% para la media de la población es el más cercano a:

A. \$71.08 to \$78.92.

B. \$73.89 to \$80.11.

C. \$74.56 to \$79.44.

\newpage

# Ejercicio 10

Best Computers, Inc., vende computadoras y partes de computadoras por correo. Una muestra de 25 pedidos recientes mostró que el tiempo medio requerido para enviar estos pedidos fue de 70 horas con una desviación estándar de muestra de 14 horas. Suponiendo que la población se distribuye normalmente, el intervalo de confianza del 99% para la media de la población es:

A. 70 ± 2.80 hours.

B. 70 ± 6.98 hours.

C. 70 ± 7.83 hours.

\newpage

# Ejercicio 11

La distribución de muestreo de una estadística es la distribución de probabilidad compuesta
de todos los posibles:

A. observaciones de la población subyacente.

B. estadísticas de muestra calculadas a partir de muestras de distintos tamaños extraídas de la misma población.

C. estadísticas de muestra calculadas a partir de muestras del mismo tamaño extraídas de la misma población.

\newpage

# Ejercicio 12

La muestra de las relaciones deuda / capital de 25 bancos estadounidenses que cotizan en bolsa a nivel fiscal fin de año 2003 es un ejemplo de:

A. una estimación puntual.

B. datos transversales.

C. una muestra aleatoria estratificada.

\newpage

# Ejercicio 13

¿Cuál de las siguientes opciones es menos probable que sea una propiedad deseable de una estimación?

A. Confiabilidad.

B. Eficiencia.

C. Consistencia.

\newpage

# Ejercicio 14

Si la varianza de la distribución de muestreo de un estimador es más pequeña que todas otros estimadores insesgados del parámetro de interés, el estimador es:

A. eficiente.

B. imparcial.

C. consistente.

\newpage

# Ejercicio 15

¿Cuál de las siguientes opciones es menos probable que sea una propiedad de la distribución del Estudiante?

A. A medida que los grados de libertad se hacen más grandes, la varianza se acerca a cero.

B. Se define por un solo parámetro, los grados de libertad, que es igual a n - 1.

C. Tiene más probabilidad en las colas y menos en el pico que un estándar.

\newpage

# Ejercicio 16

Una analista que utiliza datos históricos que no estaban disponibles públicamente en el período de tiempo que se está estudiando tendrá una muestra con:

A. parcialidad de anticipación.

B. Sesgo de período de tiempo.

C. sesgo de selección de muestra.

\newpage

# Ejercicio 17

El intervalo de confianza del 95% de la media muestral de la edad del empleado para una corporación importante es de 19 años a 44 años según una estadística z. La población de empleados es más de 5,000 y el tamaño de muestra de esta prueba es 100. Suponiendo que la población se distribuye normalmente, el error estándar de la edad media de los empleados es el más cercano a:

A. 1.96.

B. 2.58.

c. 6.38.

\newpage

# Ejercicio 18

¿Cuál de los siguientes está más **estrechamente** relacionado con el sesgo de supervivencia?

A. Estudios de precio por libro.

B. Estudios de muestreo de bonos estratificados.

C. Estudios de desempeño de fondos mutuos.

\newpage

# Ejercicio 19

¿Cuál es la estadística de prueba más apropiada para construir intervalos de confianza para la media poblacional cuando la población está distribuida normalmente, pero la varianza es desconocida?

A. La estadística z en $\alpha$ con **n** grados de libertad.

B. La estadística t en $\alpha$/2 con **n** grados de libertad.

C. La estadística t en $\alpha$/2 con n - 1 grados de libertad.

\newpage

# Ejercicio 20

Cuando se construye un intervalo de confianza para la media poblacional de una distribución no normal cuando se desconoce la varianza poblacional y el tamaño de la muestra es grande (n> 30), un analista puede aceptar el uso:

A. bien una estadística z o una estadística t.

B. solo una estadística z en $\alpha$ con **n** grados de libertad.

C. solo una estadística t en $\alpha$/2 con **n** grados de libertad.

\newpage

# Ejercicio 21

Jenny Fox evalúa a los gerentes que tienen una desviación estándar de la población de la sección transversal de rendimientos del 8%. Si los retornos son independientes en todos los gerentes, ¿qué cantidad de muestra necesita Fox entonces el error estándar de los medios de muestra es 1.265%?

A. 7.

B. 30.

C. 40.

\newpage

# Ejercicio 22

Los rendimientos anuales de acciones pequeñas tienen una media poblacional del 20%. Si los rendimientos se distribuyen normalmente, un intervalo de confianza del 90% en los rendimientos medios durante un período de 5 años es:

A. 5.40% a 18.60%.

B. -2.75% a 26.75%

C. -5.52% a 29.52%

\newpage

# Ejercicio 23

Usando un muestreo aleatorio, un gerente quiere construir una cartera de 50 acciones que se aproximará a los rendimientos de un amplio índice de mercado que contiene 200 acciones. Explique cómo pudo utilizar el muestreo aleatorio de muestra y el muestreo aleatorio estratificado para seleccionar stocks del índice y las posibles ventajas del muestreo aleatorio estratificado.

\newpage

# Ejercicio 24

Un analista ha tomado una muestra aleatoria de 50 observaciones de una población para la cual quiere estimar el promedio de la población. Ella cree que la distribución de la población está negativamente sesgada.

A. ¿Puede usar la media de la muestra para estimar la media de la población y construir un intervalo de confianza? Explique.

B. ¿Cuáles son las propiedades estadísticas deseables de un estimador?

C. ¿Cuál de estas propiedades tiene la muestra media como un estimador de la media poblacional?

\newpage

# Ejercicio 25

Una muestra aleatoria de las estimaciones de ganancias de los analistas tiene una media de \$2.84 y una desviación estándar de \$0.40. ¿Qué podemos decir sobre el intervalo de confianza del 90% para las ganancias del próximo período si:

A. el tamaño de muestra es 20?

B. el tamaño de muestra es 40? 

¿Qué enunciado probabilístico podríamos hacer al nivel de confianza del 90% si:

C. el tamaño de muestra fue 15?

D. el tamaño de muestra fue 60?


